import { Tool } from "./types";

export const tools: Tool[] = [
  {
    id: "1",
    name: "RealEstateAI CRM Pro",
    slug: "realestate-ai-crm-pro",
    description:
      "The most intelligent CRM built specifically for real estate agents. AI-powered lead scoring, automated follow-ups, and predictive client insights.",
    longDescription:
      "RealEstateAI CRM Pro revolutionizes how agents manage their client relationships. Using advanced machine learning, it automatically scores and prioritizes leads based on buying signals, engagement patterns, and market data. The AI assistant drafts personalized follow-up emails, suggests optimal contact times, and predicts which leads are most likely to convert. Integration with MLS systems means your pipeline is always up to date.",
    category: "crm",
    rating: 4.8,
    reviewCount: 342,
    pricing: [
      {
        name: "Starter",
        price: 49,
        period: "month",
        features: [
          "Up to 500 contacts",
          "AI lead scoring",
          "Email templates",
          "Basic analytics",
        ],
      },
      {
        name: "Professional",
        price: 99,
        period: "month",
        features: [
          "Unlimited contacts",
          "Advanced AI insights",
          "SMS automation",
          "MLS integration",
          "Team collaboration",
        ],
      },
      {
        name: "Enterprise",
        price: 199,
        period: "month",
        features: [
          "Everything in Pro",
          "Custom AI models",
          "API access",
          "Dedicated support",
          "White-label options",
        ],
      },
    ],
    features: [
      "AI-powered lead scoring and prioritization",
      "Automated follow-up sequences",
      "Predictive client behavior analysis",
      "MLS and IDX integration",
      "Smart email drafting assistant",
      "Pipeline analytics dashboard",
      "Mobile app with AI notifications",
      "Transaction timeline tracking",
    ],
    pros: [
      "Best-in-class AI lead scoring accuracy",
      "Intuitive interface designed for agents",
      "Excellent MLS integration",
      "Responsive customer support",
    ],
    cons: [
      "Higher price point than basic CRMs",
      "Learning curve for advanced AI features",
      "Limited customization on Starter plan",
    ],
    website: "https://example.com/crm-pro",
    affiliateUrl: "#",
    logo: "🏠",
    badge: "Editor's Choice",
    lastUpdated: "2026-03-15",
  },
  {
    id: "2",
    name: "StageAI",
    slug: "stageai",
    description:
      "Transform empty rooms into beautifully staged spaces in seconds. AI-powered virtual staging that looks indistinguishable from real photography.",
    longDescription:
      "StageAI uses cutting-edge generative AI to virtually stage any room in seconds. Simply upload a photo of an empty space, choose a style (modern, traditional, minimalist, luxury), and the AI generates photorealistic staging that passes the trained eye test. With support for commercial and residential spaces, customizable furniture styles, and batch processing, StageAI has become the go-to tool for agents who want to showcase properties at their best without the cost of physical staging.",
    category: "virtual-staging",
    rating: 4.7,
    reviewCount: 528,
    pricing: [
      {
        name: "Pay Per Image",
        price: 29,
        period: "month",
        features: [
          "10 staged images/month",
          "5 design styles",
          "HD output",
          "24-hour turnaround",
        ],
      },
      {
        name: "Pro",
        price: 59,
        period: "month",
        features: [
          "50 staged images/month",
          "All design styles",
          "4K output",
          "Instant generation",
          "Commercial spaces",
        ],
      },
      {
        name: "Agency",
        price: 99,
        period: "month",
        features: [
          "Unlimited images",
          "Custom styles",
          "API access",
          "Team accounts",
          "Priority support",
          "Batch processing",
        ],
      },
    ],
    features: [
      "Photorealistic AI virtual staging",
      "15+ design styles and themes",
      "Batch processing for multiple rooms",
      "Before/after comparison views",
      "Commercial and residential support",
      "Custom furniture placement",
      "4K resolution output",
      "30-second generation time",
    ],
    pros: [
      "Incredibly realistic output quality",
      "Fastest generation time on the market",
      "Wide variety of design styles",
      "Affordable compared to physical staging",
    ],
    cons: [
      "Occasional artifacts in complex rooms",
      "Limited outdoor/garden staging",
      "Pay-per-image model can add up",
    ],
    website: "https://example.com/stageai",
    affiliateUrl: "#",
    logo: "🎨",
    badge: "Most Popular",
    lastUpdated: "2026-03-10",
  },
  {
    id: "3",
    name: "LeadGenius RE",
    slug: "leadgenius-re",
    description:
      "AI-powered lead generation that finds motivated buyers and sellers before your competition. Predictive analytics meets real estate prospecting.",
    longDescription:
      "LeadGenius RE combines big data analytics with AI to identify potential buyers and sellers who are most likely to transact in the near future. By analyzing public records, social signals, life events, and market patterns, the platform surfaces high-quality leads before they even start their home search. The AI continuously learns from your conversion data to improve targeting over time.",
    category: "lead-generation",
    rating: 4.5,
    reviewCount: 215,
    pricing: [
      {
        name: "Agent",
        price: 79,
        period: "month",
        features: [
          "100 leads/month",
          "AI lead scoring",
          "Email integration",
          "Basic targeting",
        ],
      },
      {
        name: "Team",
        price: 199,
        period: "month",
        features: [
          "500 leads/month",
          "Advanced AI targeting",
          "CRM integration",
          "Territory mapping",
          "Lead routing",
        ],
      },
      {
        name: "Brokerage",
        price: 299,
        period: "month",
        features: [
          "Unlimited leads",
          "Custom AI models",
          "White-label",
          "API access",
          "Dedicated account manager",
        ],
      },
    ],
    features: [
      "Predictive seller identification",
      "Buyer intent signal analysis",
      "Automated prospecting campaigns",
      "Territory-based lead generation",
      "CRM auto-sync",
      "Life event tracking (divorce, job change, etc.)",
      "Market timing predictions",
      "ROI tracking dashboard",
    ],
    pros: [
      "Highly accurate predictive models",
      "Saves hours of manual prospecting",
      "Integrates with major CRMs",
      "Excellent ROI for active agents",
    ],
    cons: [
      "Requires 2-3 months to optimize AI model",
      "Higher price point for solo agents",
      "Data accuracy varies by market",
    ],
    website: "https://example.com/leadgenius",
    affiliateUrl: "#",
    logo: "🎯",
    lastUpdated: "2026-03-12",
  },
  {
    id: "4",
    name: "ListingWriter AI",
    slug: "listingwriter-ai",
    description:
      "Generate compelling listing descriptions, social media posts, and marketing copy in seconds. Trained on millions of high-converting real estate listings.",
    longDescription:
      "ListingWriter AI is the content creation powerhouse for real estate professionals. Trained specifically on millions of real estate listings, marketing emails, and social media posts, it generates copy that sells. Input your property details and the AI crafts compelling descriptions optimized for different platforms — MLS, Zillow, social media, email campaigns, and print materials. It even adapts tone for luxury, starter homes, commercial, or investment properties.",
    category: "marketing",
    rating: 4.6,
    reviewCount: 891,
    pricing: [
      {
        name: "Basic",
        price: 19,
        period: "month",
        features: [
          "20 listings/month",
          "MLS descriptions",
          "3 writing styles",
          "Basic editing",
        ],
      },
      {
        name: "Pro",
        price: 39,
        period: "month",
        features: [
          "Unlimited listings",
          "All platforms",
          "Social media posts",
          "Email campaigns",
          "SEO optimization",
        ],
      },
      {
        name: "Agency",
        price: 49,
        period: "month",
        features: [
          "Everything in Pro",
          "Team accounts",
          "Brand voice training",
          "API access",
          "Analytics",
        ],
      },
    ],
    features: [
      "AI listing description generator",
      "Social media post creator",
      "Email campaign copywriting",
      "Multi-platform optimization",
      "Luxury property specialist mode",
      "Multilingual support (8 languages)",
      "SEO keyword integration",
      "Brand voice customization",
    ],
    pros: [
      "Incredibly fast — descriptions in seconds",
      "Very affordable pricing",
      "Great quality for MLS listings",
      "Easy to use, minimal learning curve",
    ],
    cons: [
      "Sometimes needs human editing for luxury properties",
      "Limited image caption generation",
      "Brand voice training takes time to dial in",
    ],
    website: "https://example.com/listingwriter",
    affiliateUrl: "#",
    logo: "✍️",
    badge: "Best Value",
    lastUpdated: "2026-03-08",
  },
  {
    id: "5",
    name: "PropVal Analytics",
    slug: "propval-analytics",
    description:
      "AI-driven property valuation and market analytics. Get instant CMAs, market forecasts, and investment analysis powered by machine learning.",
    longDescription:
      "PropVal Analytics brings institutional-grade property analytics to individual agents and small brokerages. The AI analyzes comparable sales, market trends, economic indicators, and hyperlocal data to generate accurate property valuations and market forecasts. Whether you're pricing a listing, advising an investor, or creating a CMA for a seller presentation, PropVal gives you data-backed confidence in your numbers.",
    category: "analytics",
    rating: 4.4,
    reviewCount: 167,
    pricing: [
      {
        name: "Agent",
        price: 99,
        period: "month",
        features: [
          "50 valuations/month",
          "Basic CMA reports",
          "Market trends",
          "Single market",
        ],
      },
      {
        name: "Professional",
        price: 199,
        period: "month",
        features: [
          "200 valuations/month",
          "Advanced CMA",
          "Investment analysis",
          "5 markets",
          "API access",
        ],
      },
      {
        name: "Enterprise",
        price: 399,
        period: "month",
        features: [
          "Unlimited valuations",
          "Custom reports",
          "Unlimited markets",
          "White-label",
          "Dedicated analyst",
        ],
      },
    ],
    features: [
      "Instant AI property valuations",
      "Automated CMA generation",
      "Market trend forecasting",
      "Investment ROI calculator",
      "Neighborhood analytics",
      "Price prediction models",
      "Comparable sales analysis",
      "Custom report branding",
    ],
    pros: [
      "Highly accurate valuations (within 3% of sale price)",
      "Beautiful, client-ready reports",
      "Forecasting gives competitive advantage",
      "Great for investor-focused agents",
    ],
    cons: [
      "Premium pricing not ideal for new agents",
      "Data coverage varies in rural markets",
      "Steep learning curve for advanced features",
    ],
    website: "https://example.com/propval",
    affiliateUrl: "#",
    logo: "📊",
    lastUpdated: "2026-03-05",
  },
  {
    id: "6",
    name: "ChatHome AI",
    slug: "chathome-ai",
    description:
      "24/7 AI chatbot for your real estate website. Qualifies leads, answers property questions, and books showings while you sleep.",
    longDescription:
      "ChatHome AI is a specialized real estate chatbot that lives on your website and handles inquiries around the clock. Unlike generic chatbots, it understands real estate terminology, can answer detailed questions about listings (when connected to your IDX feed), qualify leads based on your criteria, and even schedule showings directly into your calendar. The AI learns from your past conversations to improve its responses over time.",
    category: "chatbots",
    rating: 4.3,
    reviewCount: 203,
    pricing: [
      {
        name: "Starter",
        price: 39,
        period: "month",
        features: [
          "1 website",
          "500 conversations/month",
          "Lead capture",
          "Basic Q&A",
        ],
      },
      {
        name: "Professional",
        price: 89,
        period: "month",
        features: [
          "3 websites",
          "Unlimited conversations",
          "IDX integration",
          "Showing scheduler",
          "CRM sync",
        ],
      },
      {
        name: "Team",
        price: 149,
        period: "month",
        features: [
          "10 websites",
          "Everything in Pro",
          "Custom training",
          "Lead routing",
          "Analytics dashboard",
        ],
      },
    ],
    features: [
      "24/7 automated lead qualification",
      "IDX/MLS listing integration",
      "Showing scheduling with calendar sync",
      "Multi-language support",
      "Custom conversation flows",
      "Lead scoring and routing",
      "CRM auto-sync (50+ integrations)",
      "Human handoff capability",
    ],
    pros: [
      "Captures leads you'd otherwise miss overnight",
      "Easy setup — live in under 30 minutes",
      "Natural conversational AI that doesn't feel robotic",
      "Excellent calendar integration",
    ],
    cons: [
      "Occasional misunderstandings with complex queries",
      "IDX integration requires Professional plan",
      "Limited customization on Starter plan",
    ],
    website: "https://example.com/chathome",
    affiliateUrl: "#",
    logo: "💬",
    lastUpdated: "2026-03-01",
  },
  {
    id: "7",
    name: "DealFlow AI",
    slug: "dealflow-ai",
    description:
      "Automate your transaction management with AI. From contract to closing, DealFlow handles the paperwork so you can focus on selling.",
    longDescription:
      "DealFlow AI transforms the most tedious part of real estate — transaction management. The AI reads and extracts key data from contracts, tracks deadlines and contingencies, sends automated reminders to all parties, and flags potential compliance issues before they become problems. Integration with DocuSign, dotloop, and major brokerages means your documents flow seamlessly from listing to closing.",
    category: "transaction",
    rating: 4.5,
    reviewCount: 156,
    pricing: [
      {
        name: "Solo Agent",
        price: 59,
        period: "month",
        features: [
          "10 transactions/month",
          "AI document reading",
          "Deadline tracking",
          "Email reminders",
        ],
      },
      {
        name: "Team",
        price: 129,
        period: "month",
        features: [
          "50 transactions/month",
          "Advanced AI extraction",
          "Compliance checks",
          "DocuSign integration",
          "Team dashboard",
        ],
      },
      {
        name: "Brokerage",
        price: 199,
        period: "month",
        features: [
          "Unlimited transactions",
          "Custom workflows",
          "Audit trail",
          "API access",
          "Dedicated support",
        ],
      },
    ],
    features: [
      "AI-powered contract data extraction",
      "Automated deadline and contingency tracking",
      "Compliance verification engine",
      "DocuSign and dotloop integration",
      "Automated party notifications",
      "Transaction timeline visualization",
      "Document checklist management",
      "Closing cost calculator",
    ],
    pros: [
      "Dramatically reduces admin time",
      "Catches compliance issues early",
      "Great integration ecosystem",
      "Clear transaction timeline view",
    ],
    cons: [
      "Requires initial setup for custom workflows",
      "AI extraction occasionally needs correction",
      "Limited state-specific compliance rules",
    ],
    website: "https://example.com/dealflow",
    affiliateUrl: "#",
    logo: "📋",
    lastUpdated: "2026-02-28",
  },
  {
    id: "8",
    name: "PhotoPerfect RE",
    slug: "photoperfect-re",
    description:
      "AI photo enhancement and virtual tour creation for real estate listings. Turn amateur photos into professional-quality images instantly.",
    longDescription:
      "PhotoPerfect RE uses specialized AI models trained on millions of professional real estate photos to enhance your listing images. It automatically corrects lighting, straightens perspectives, enhances colors, removes unwanted objects, and even replaces dull skies with beautiful ones. The virtual tour builder stitches your photos into immersive 360° walkthroughs that you can embed on any listing page.",
    category: "photo-video",
    rating: 4.6,
    reviewCount: 412,
    pricing: [
      {
        name: "Basic",
        price: 24,
        period: "month",
        features: [
          "50 photos/month",
          "Auto-enhance",
          "Sky replacement",
          "Basic editing",
        ],
      },
      {
        name: "Professional",
        price: 49,
        period: "month",
        features: [
          "200 photos/month",
          "Virtual tours",
          "Object removal",
          "HDR merging",
          "Batch processing",
        ],
      },
      {
        name: "Studio",
        price: 79,
        period: "month",
        features: [
          "Unlimited photos",
          "Everything in Pro",
          "Video enhancement",
          "Drone footage editing",
          "Brand watermarks",
        ],
      },
    ],
    features: [
      "One-click AI photo enhancement",
      "Automatic sky replacement",
      "Perspective correction",
      "Object and clutter removal",
      "Virtual tour builder",
      "HDR photo merging",
      "Batch processing (up to 100 photos)",
      "Video stabilization and enhancement",
    ],
    pros: [
      "Dramatic quality improvement in seconds",
      "Sky replacement looks incredibly natural",
      "Virtual tour builder is easy to use",
      "Great value for the price",
    ],
    cons: [
      "Object removal struggles with large items",
      "Virtual tours limited to photo-based (no 3D)",
      "Requires decent source photos for best results",
    ],
    website: "https://example.com/photoperfect",
    affiliateUrl: "#",
    logo: "📸",
    lastUpdated: "2026-03-14",
  },
];
